apiVersion: v1
kind: Service
metadata:
  name: shipfast-status-api
  namespace: shipfast
spec:
  type: ClusterIP
  selector:
    app: shipfast-status-api
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
